<a href="https://colab.research.google.com/github/shreyamaddheshiya/Batch-2027-Data-Analytics-Workshop-19.02.2026-to-17.03.2026/blob/main/linearegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import statistics
import numpy as np

numbers = [10, 20, 30, 40, 50, 20]

mean = statistics.mean(numbers)
median = statistics.median(numbers)
mode = statistics.mode(numbers)
variance = statistics.variance(numbers)
std_dev = statistics.stdev(numbers)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Max and Min
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape (2x3 matrix)
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

# Element-wise multiplication
result = arr * 2
print("Element-wise Multiplication:\n", result)

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise Multiplication:
 [ 2  4  6  8 10 12]


In [4]:
import numpy as np

# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix Multiplication
print("Multiplication:\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [6]:
import numpy as np

random_arr = np.random.randint(1, 100, 10)

print("Array:", random_arr)
print("Mean:", np.mean(random_arr))
print("Standard Deviation:", np.std(random_arr))
print("Minimum:", np.min(random_arr))
print("Maximum:", np.max(random_arr))

Array: [98 60  3 42 83 25 98 15 57 65]
Mean: 54.6
Standard Deviation: 31.594936303148327
Minimum: 3
Maximum: 98


In [7]:
import numpy as np
from scipy import stats

data = [10, 12, 9, 11, 10, 13, 12]

# Mean using scipy.stats
mean = stats.tmean(data)
print("Mean:", mean)

# One-sample t-test (compare with population mean = 10)
t_stat, p_value = stats.ttest_1samp(data, 10)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

Mean: 11.0
T-Statistic: 1.8708286933869707
P-Value: 0.1105517404022668


In [8]:
from scipy import integrate
import numpy as np

# Function: f(x) = x^2
def func(x):
    return x**2

result, error = integrate.quad(func, 0, 3)

print("Integration Result:", result)
print("Estimated Error:", error)

Integration Result: 9.000000000000002
Estimated Error: 9.992007221626411e-14


In [9]:
from scipy import optimize

# Function: f(x) = x^2 + 4x + 4
def func(x):
    return x**2 + 4*x + 4

result = optimize.minimize(func, x0=0)

print("Minimum Value:", result.fun)
print("Minimum at x =", result.x)

Minimum Value: 0.0
Minimum at x = [-2.00000002]


In [11]:
import pandas as pd

# First DataFrame
data1 = {
    "Name": ['Jai', 'Prince', 'Gaurav', 'Anuj'],
    "Age": [27, 24, 22, 32],
    "Address": ['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
    "Quali": ["M Sc", 'MA', 'MCA', "Phd"]
}

df = pd.DataFrame(data1)

# Select specific columns
print(df[['Name', 'Quali']])


# Second Part
# Make sure nba.csv file exists in same folder
data2 = pd.read_csv('nba.csv')

# Set index properly (if column name is 'Name' not 'name')
data2.set_index('Name', inplace=True)

# Fetch rows safely
try:
    first = data2.loc["Avery Bradley"]
    second = data2.loc["R.J. Hunter"]

    print("\n\n", first)
    print("\n\n", second)

except KeyError:
    print("Player not found in dataset.")

     Name Quali
0     Jai  M Sc
1  Prince    MA
2  Gaurav   MCA
3    Anuj   Phd


FileNotFoundError: [Errno 2] No such file or directory: 'nba.csv'

In [12]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
data2 = pd.read_csv('nba.csv')


Saving images.png to images.png


FileNotFoundError: [Errno 2] No such file or directory: 'nba.csv'

In [13]:
from google.colab import files
uploaded = files.upload()

Saving nba.csv.png to nba.csv.png


In [14]:
import pandas as pd
data2 = pd.read_csv('nba.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'nba.csv'

In [15]:
import pandas as pd
data2 = pd.read_csv('nba.csv.png')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

In [16]:
# WAP to implement Simple Linear Regression

# Sample data
x = [1, 2, 3, 4, 5]
y = [2, 4, 5, 4, 5]

n = len(x)

sum_x = sum(x)
sum_y = sum(y)
sum_xy = sum([x[i]*y[i] for i in range(n)])
sum_x2 = sum([x[i]**2 for i in range(n)])

# Calculate slope (b1)
b1 = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x**2)

# Calculate intercept (b0)
b0 = (sum_y - b1 * sum_x) / n

print("Slope (b1):", b1)
print("Intercept (b0):", b0)

# Prediction
x_new = 6
y_pred = b0 + b1 * x_new
print("Predicted value for x =", x_new, "is", y_pred)

Slope (b1): 0.6
Intercept (b0): 2.2
Predicted value for x = 6 is 5.8
