In [2]:
import statistics
import numpy as np

numbers = [10, 20, 30, 40, 50, 20]

mean = statistics.mean(numbers)
median = statistics.median(numbers)
mode = statistics.mode(numbers)
variance = statistics.variance(numbers)
std_dev = statistics.stdev(numbers)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Max and Min
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape (2x3 matrix)
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

# Element-wise multiplication
result = arr * 2
print("Element-wise Multiplication:\n", result)

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise Multiplication:
 [ 2  4  6  8 10 12]


In [4]:
import numpy as np

# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix Multiplication
print("Multiplication:\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
